create table EMPLOYEE(
    id int generated by default as identity,
    name varchar(10),
    aadhar varchar(10),
    age int,
    dept varchar(50),
    city varchar(50),
    dob date,
    primary key (id)
);
